name: "" 
namespace: streamforge 
replicas: 2
image: 
  repo: "" 
  tag: "dev" 
serviceAccount: 
  roleArn: "" 
containerPort: 8080
env: {}
resources: 
  requests: { cpu: 50m, memory: 128Mi }
  limits: { cpu: 250m, memory: 256Mi }
rollout:
  enabled: false
  steps: 
    - setWeight: 10
    - pause: { duration: 30 }
    - setWeight: 25
    - pause: { duration: 30 }
    - setWeight: 50
    - pause: { duration: 30 }
  analysis:
    successRate: "0.95"
    interval: 30s
    failureLimit: 1