{{- if .Values.rollout.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  podTargetLabels:
    - rollouts-pod-template-hash
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end}}