apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: catalog 
  namespace: argocd 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source: 
    repoURL: https://github.com/Tooltu-deve/StreamForge-Gitops.git
    targetRevision: main 
    path: charts/service
    helm: 
      valueFiles:
        - ../../values/catalog.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: streamforge 
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]