name: "" 
namespace: streamforge 
replicas: 1 
image: 
  repo: "" 
  tag: "dev" 
serviceAccount: 
  roleArn: "" 
env: {}
resources: 
  requests: { cpu: 250m, memory: 512Mi }
  limits: { cpu: "1", memory: 1Gi }
nodeSelector: {}
tolerations: []
keda: 
  enabled: false 
  maxReplicas: 4
  queueUrl: "" 